name: Build, UnitTests and End-2-end tests
on:
  push:
    branches-ignore:
      - 'master'
jobs:

  build-server:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build .NET Web API
        run: dotnet build

  run-server-tests:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: 'server.tests'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build .NET Web API
        run: dotnet build

      - name: Run .NET Web API Tests
        run: dotnet test

  build-and-test-client:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        shell: bash
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Install Angular dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Build Angular app
        run: npm run test

  cypress-e2e-and-component-tests-on-google-chrome:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: serve Front-End
        working-directory: client
        run: |
          npm ci
          npm start &

      - name: start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0 # already includes "Waiting for MongoDB to accept connections" at the end
        with:
          mongodb-version: '6.0'

      - name: Build and Run Back-End
        working-directory: server
        run: dotnet build && dotnet run &

      - name: run cypress e2e
        uses: cypress-io/github-action@v6.6.0
        with:
          working-directory: client
          spec: cypress/e2e/**/*.cy.ts
          if-no-files-found: error
          browser: chrome
          wait-on: 'http://localhost:5126/swagger/index.html, http://localhost:4200'

      - name: run cypress component tests
        uses: cypress-io/github-action@v6.6.0
        with:
          working-directory: client
          spec: src/app/**/*.cy.ts
          component: true
          if-no-files-found: error
          browser: chrome
          wait-on: 'http://localhost:5126/swagger/index.html, http://localhost:4200'

## TODO: Move into seperate files and reuse them, to make this more readable? or make use of matrixes for multi browser
