name: Build and Deploy Angular and .NET Web API
on: push
jobs:

  build-server:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build .NET Web API
        run: dotnet build

  build-and-run-server-tests:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash
        working-directory: server.tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build .NET Web API
        run: dotnet build

      - name: Run .NET Web API Tests
        run: dotnet test

  build-angular:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Install Angular dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

  # setup-mongodb:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Git checkout
  #     uses: actions/checkout@v4

  #   - name: Start MongoDB
  #     uses: supercharge/mongodb-github-action@1.10.0
  #     with:
  #       mongodb-version: '6.0'

  cypress-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'

      - name: serve Front-End
        working-directory: client
        run: |
          npm ci
          npm start &

      - name: Build and Run Back-End
        working-directory: server
        run: |
          dotnet build
          dotnet run &

      - name: Cypress run
        uses: cypress-io/github-action@v6.6.0
        with:
          working-directory: client
          spec: cypress/e2e/**/*.cy.ts
          # if-no-files-found: error
          browser: chrome
          wait-on: |
            "http://localhost:4200"
            "http://localhost:5126"
            "http://127.0.0.1:21017"
